### ISSUE TITLE
Can't deploy to prod

### ISSUE THREAD

**Issue by tobiasmllr** [bcgov/nr-hydrometric-rating-curve#127]
Hello, I adjusted the CSRF origin in the openshift django env to make the vanity url work. Now the deployment to prod failed:
```
Warning: resource routes/nr-hydrometric-rating-curve-prod-frontend is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by oc apply. oc apply should only be used on resources created declaratively by either oc create --save-config or oc apply. The missing annotation will be patched automatically.
The Route "nr-hydrometric-rating-curve-prod-frontend" is invalid: spec.host: Invalid value: "nr-hydrometric-rating-curve-prod-frontend.apps.silver.devops.gov.bc.ca": field is immutable
horizontalpodautoscaler.autoscaling/nr-hydrometric-rating-curve-prod-frontend configured
```

**Comment by mishraomp** [comment]
I think its failing due to the fact that there is already route with the same name, will check it 

cc @DerekRoberts

**Comment by tobiasmllr** [comment]
Weird, I just noticed that my change to main is working and live on the new URL.

**Comment by DerekRoberts** [comment]
@tobiasmllr You did everything right!  ...We just now changed the routing and retried.  The problem shouldn't reoccur, with a scripted solution on the way.
