### ISSUE TITLE
Pull requests fail due to automated naming 

### ISSUE THREAD

**Issue by tobiasmllr** [bcgov/nr-hydrometric-rating-curve#164]
Hello, somehow the automated Pull requests fail due to naming:

```
Run echo "Validation failed!  Possible reasons:"
Validation failed!  Possible reasons:
 - Forks are not supported
 - Conventional commits required for PR titles and merges
    https://www.conventionalcommits.org/en/v1.0.0/
Error: Process completed with exit code 1.
```

For example https://github.com/bcgov/nr-hydrometric-rating-curve/pull/163

Is this maybe a formatting problem?

**Comment by DerekRoberts** [comment]
@tobiasmllr Welcome back!  :)

Solved by updating our Actions (#159) and stopping toublesome Dependabot updates (#168).
