### ISSUE TITLE
Release production build failing

### ISSUE THREAD

**Issue by tobiasmllr** [bcgov/nr-hydrometric-rating-curve#192]
Hello, the release production build fails due to some expected PR number being unavailable:
https://github.com/bcgov/nr-hydrometric-rating-curve/actions/runs/11328718083/job/31502688805

Steps I followed:
- Updated 'main'
- Test-version built successfully
- Created new version v1.0.5
- Automatic build of 'prod' for v1.0.5 failed

**Comment by mishraomp** [comment]
thanks for the issue @tobiasmllr.

@DerekRoberts for workflow_dispatch, there wont be any PR numbers,

-  should we change the https://github.com/bcgov-nr/action-get-pr to ignore workflow_dispatch. OR
-  should we change https://github.com/bcgov/quickstart-openshift-helpers/blob/main/.github/workflows/.deployer.yml to not run get pr number if tag is provided,

I prefer the 2nd option, but let you decide which one you would like, or if none of them and you want it to handle in different way.

**Comment by mishraomp** [comment]
fixed as part of #194 @tobiasmllr and latest release v1.1.0 went to prod
