### ISSUE TITLE
test build fails

### ISSUE THREAD

**Issue by tobiasmllr** [bcgov/nr-hydrometric-rating-curve#226]
Hello, there seems to be another issue with the CICD. The test deployment fails, and somehow it seems like prod is also not updated correctly after I created a new release (but that might be caching still being behind?)

https://github.com/bcgov/nr-hydrometric-rating-curve/actions/runs/12206330109/job/34055569968

`Run # Helm upgrade/rollout - atomic, timeout
Error: UPGRADE FAILED: another operation (install/upgrade/rollback) is in progress
Error: Process completed with exit code 1.`

Thanks for the quick fix last time, @DerekRoberts ! Really appreciate it

**Comment by DerekRoberts** [comment]
@tobiasmllr I'm off today, but let's get this solved Monday.  Have a good weekend!  😄

**Comment by mishraomp** [comment]
its fixed @tobiasmllr , https://github.com/bcgov/nr-hydrometric-rating-curve/actions/runs/12206330109
cc @DerekRoberts

**Comment by DerekRoberts** [comment]
@mishraomp Hooray! What happened?

**Comment by mishraomp** [comment]
> [@mishraomp](https://github.com/mishraomp) Hooray! What happened?

The main merge failed 3 days ago and helm was in pending rollback state, I just deleted the charts and rerun, since there is no database and all stateless apps, it's easy delete and redeploy.
