### ISSUE TITLE
Builds fail since new github actions

### ISSUE THREAD

**Issue by tobiasmllr** [bcgov/nr-hydrometric-rating-curve#88]
/usr/bin/docker buildx build --cache-from type=gha --cache-to type=gha,mode=max --file ./frontend/Dockerfile.app --iidfile /home/runner/work/_temp/docker-actions-toolkit-gSNomR/iidfile --tag ghcr.io/bcgov/nr-hydrometric-rating-curve/rctool:87 --metadata-file /home/runner/work/_temp/docker-actions-toolkit-gSNomR/metadata-file --push ./rctool

**ERROR: unable to prepare context: path "./rctool" not found
Error: buildx failed with: ERROR: unable to prepare context: path "./rctool" not found**

It seems some path is not correct any more? the path rctool is under /frontend/

**Comment by tobiasmllr** [comment]
@DerekRoberts It appears since Friday all deployments fail again. I thought it would at least work once if it's just low on resources, but it seems all runs are failing.

```
Deployment config "nr-hydrometric-rating-curve-103-frontend" waiting on image update
Deployment config "nr-hydrometric-rating-curve-103-frontend" waiting on image update
Waiting for latest deployment config spec to be observed by the controller loop...
Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for rollout to finish: 0 out of 1 new replicas have been updated...
Waiting for rollout to finish: 0 of 1 updated replicas are available...
error: replication controller "nr-hydrometric-rating-curve-103-frontend-1" has failed progressing
Error: Process completed with exit code 1.
```

**Comment by DerekRoberts** [comment]
@tobiasmllr How about taking this to MS Teams?  Working with OpenShift can be an adventure...

**Comment by DerekRoberts** [comment]
@mishraomp Immediately found a cleanup bug!  We're out of resources.  Fixing now.
